# Generated by Django 6.1 on 2026-08-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_by_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('postponed', 'Pospuesta')], default='pending', max_length=20),
        ),
    ]
